<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { Check, ListPlus, RefreshCw, ShieldAlert, ShieldCheck, X } from "lucide-vue-next";
import AppDrawer from "../../components/AppDrawer.vue";
import AppPagination from "../../components/AppPagination.vue";
import ConfigurationCenterView from "../configuration/ConfigurationCenterView.vue";
import { authState } from "../../auth";
import { changeRiskListStatus, createRiskList, getRiskEvents, getRiskLists, getRiskOverview, reviewRiskEvent, type RiskEvent, type RiskListEntry } from "./api";
const emit = defineEmits<{ notice: [message: string] }>();
const tab = ref<"events" | "policies" | "lists">("events");
const loading = ref(false);
const overview = ref({ openEvents: 0, reviewEvents: 0, rejectedEvents: 0, events24h: 0 });
const events = ref<RiskEvent[]>([]); const lists = ref<RiskListEntry[]>([]);
const eventPage = ref({ page: 1, pageSize: 20, total: 0 }); const listPage = ref({ page: 1, pageSize: 20, total: 0 });
const filters = ref({ status: "", level: "", merchantId: "" }); const listType = ref("");
const selected = ref<RiskEvent | null>(null); const drawer = ref<"event" | "list" | null>(null);
const reviewNote = ref(""); const saving = ref(false);
const listForm = ref({ listType: "BLACK", subjectType: "EMAIL", subjectValue: "", label: "", expiresAt: "" });
const canReview = computed(() => (authState.user?.roles || []).some((role) => role === "RISK" || role === "ADMIN"));
const load = async (page = eventPage.value.page) => { loading.value = true; try { const [summary, result] = await Promise.all([getRiskOverview(), getRiskEvents({ ...filters.value, page, pageSize: eventPage.value.pageSize })]); overview.value = summary; events.value = result.items; eventPage.value = { page: result.page, pageSize: result.pageSize, total: result.total }; } catch (error) { emit("notice", error instanceof Error ? error.message : "风险事件加载失败"); } finally { loading.value = false; } };
const loadLists = async (page = listPage.value.page) => { loading.value = true; try { const result = await getRiskLists({ type: listType.value, page, pageSize: listPage.value.pageSize }); lists.value = result.items; listPage.value = { page: result.page, pageSize: result.pageSize, total: result.total }; } catch (error) { emit("notice", error instanceof Error ? error.message : "名单加载失败"); } finally { loading.value = false; } };
const openEvent = (event: RiskEvent) => { selected.value = event; reviewNote.value = ""; drawer.value = "event"; };
const review = async (decision: "PASS" | "REJECT") => { if (!selected.value || !reviewNote.value.trim()) return; saving.value = true; try { await reviewRiskEvent(selected.value.eventId, decision, reviewNote.value.trim()); drawer.value = null; emit("notice", decision === "PASS" ? "风险事件已放行" : "风险事件已拒绝"); await load(); } catch (error) { emit("notice", error instanceof Error ? error.message : "审核失败"); } finally { saving.value = false; } };
const saveList = async () => { if (!listForm.value.subjectValue || !listForm.value.label) return; saving.value = true; try { await createRiskList({ ...listForm.value, expiresAt: listForm.value.expiresAt || undefined }); drawer.value = null; listForm.value = { listType: "BLACK", subjectType: "EMAIL", subjectValue: "", label: "", expiresAt: "" }; emit("notice", "名单条目已新增，原始标识仅用于计算哈希"); await loadLists(1); } catch (error) { emit("notice", error instanceof Error ? error.message : "新增名单失败"); } finally { saving.value = false; } };
const toggleList = async (entry: RiskListEntry) => { try { await changeRiskListStatus(entry.entryId, entry.status === "ACTIVE" ? "DISABLED" : "ACTIVE"); await loadLists(); } catch (error) { emit("notice", error instanceof Error ? error.message : "状态更新失败"); } };
onMounted(load);
</script>
<template>
  <section class="panel workspace-panel risk-workspace">
    <div class="panel-title"><div><span class="eyebrow">RISK CONTROL</span><h3>风控工作台</h3></div><button class="outline-btn" @click="tab === 'lists' ? loadLists() : load()"><RefreshCw :size="16" />刷新</button></div>
    <div class="risk-metrics"><article><span>待处理事件</span><strong>{{ overview.openEvents }}</strong><small>需要风控关注</small></article><article><span>人工审核队列</span><strong>{{ overview.reviewEvents }}</strong><small>命中 REVIEW 策略</small></article><article><span>拒绝决策</span><strong>{{ overview.rejectedEvents }}</strong><small>含策略与人工拒绝</small></article><article><span>近 24 小时事件</span><strong>{{ overview.events24h }}</strong><small>实时风险进入量</small></article></div>
    <div class="risk-tabs"><button :class="{ active: tab === 'events' }" @click="tab = 'events'; load(1)">风险事件</button><button :class="{ active: tab === 'policies' }" @click="tab = 'policies'">策略中心</button><button :class="{ active: tab === 'lists' }" @click="tab = 'lists'; loadLists(1)">名单管理</button></div>
    <template v-if="tab === 'events'"><div class="risk-filters"><select v-model="filters.status"><option value="">全部状态</option><option value="OPEN">待处理</option><option value="RESOLVED">已结案</option></select><select v-model="filters.level"><option value="">全部等级</option><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select><input v-model="filters.merchantId" placeholder="商户 ID" @keyup.enter="load(1)" /><button class="outline-btn" @click="load(1)">筛选</button></div><div v-if="loading" class="empty">加载中…</div><div v-else-if="!events.length" class="empty">当前筛选条件下暂无风险事件</div><div v-else class="configuration-table-wrap"><table class="data-table risk-table"><thead><tr><th>风险事件</th><th>命中策略</th><th>风险等级</th><th>处置状态</th><th>发生时间</th><th></th></tr></thead><tbody><tr v-for="event in events" :key="event.eventId"><td><strong>{{ event.merchantId }}</strong><small class="table-subtext">{{ event.orderId || '未关联订单' }} · {{ event.reason }}</small></td><td>{{ event.policyName || event.policyId || '名单 / 系统规则' }}<small class="table-subtext">{{ event.decision }}</small></td><td><span class="risk-level" :class="'risk-' + event.riskLevel.toLowerCase()">{{ event.riskLevel }}</span></td><td><span class="status-badge" :class="event.status === 'RESOLVED' ? 'st-active' : 'st-pending'">{{ event.reviewDecision || event.status }}</span></td><td class="mono">{{ event.createdAt }}</td><td><button class="icon-btn" title="查看与审核" @click="openEvent(event)"><ShieldAlert :size="16" /></button></td></tr></tbody></table></div><AppPagination :page="eventPage.page" :page-size="eventPage.pageSize" :total="eventPage.total" noun="条风险事件" @change="load" /></template>
    <template v-else-if="tab === 'policies'"><div class="risk-policy-guide"><ShieldCheck :size="22" /><div><strong>策略配置与版本发布</strong><p>策略变更先进入草稿版本，再经审核和发布生效。运行时已支持商户、产品、国家、币种与金额阈值条件；名单和频次维度将在后续规则执行器中继续扩展。</p></div></div><ConfigurationCenterView section="risk" @notice="emit('notice', $event)" /></template>
    <template v-else><div class="risk-list-toolbar"><select v-model="listType" @change="loadLists(1)"><option value="">全部名单</option><option value="BLACK">黑名单</option><option value="WHITE">白名单</option><option value="GREY">灰名单</option></select><button v-if="canReview" class="primary-btn" @click="drawer = 'list'"><ListPlus :size="16" />新增名单</button></div><div v-if="loading" class="empty">加载中…</div><div v-else-if="!lists.length" class="empty">暂无名单条目</div><div v-else class="configuration-table-wrap"><table class="data-table risk-table"><thead><tr><th>类型</th><th>对象</th><th>标签</th><th>有效期</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="entry in lists" :key="entry.entryId"><td><span class="risk-list-type" :class="'list-' + entry.listType.toLowerCase()">{{ entry.listType }}</span></td><td><strong>{{ entry.subjectType }}</strong><small class="table-subtext mono">{{ entry.subjectHash.slice(0, 16) }}...</small></td><td>{{ entry.label }}</td><td>{{ entry.expiresAt || '长期有效' }}</td><td><span class="status-badge" :class="entry.status === 'ACTIVE' ? 'st-active' : 'st-disabled'">{{ entry.status }}</span></td><td><button v-if="canReview" class="icon-btn" title="切换名单状态" @click="toggleList(entry)"><RefreshCw :size="15" /></button></td></tr></tbody></table></div><AppPagination :page="listPage.page" :page-size="listPage.pageSize" :total="listPage.total" noun="条名单" @change="loadLists" /></template>
    <AppDrawer v-if="drawer === 'event' && selected" title="风险事件处置" description="RISK REVIEW" @close="drawer = null"><div class="risk-detail"><span class="risk-level" :class="'risk-' + selected.riskLevel.toLowerCase()">{{ selected.riskLevel }}</span><h4>{{ selected.reason }}</h4><dl><div><dt>商户</dt><dd>{{ selected.merchantId }}</dd></div><div><dt>订单</dt><dd>{{ selected.orderId || '--' }}</dd></div><div><dt>策略</dt><dd>{{ selected.policyName || selected.policyId || '--' }}</dd></div><div><dt>关联对象</dt><dd>{{ selected.subjectType }} {{ selected.subjectMasked }}</dd></div></dl><template v-if="selected.status !== 'RESOLVED' && canReview"><label>处置说明<textarea v-model="reviewNote" maxlength="512" placeholder="填写核查依据与处置结论" /></label><div class="button-row"><button class="primary-btn" :disabled="saving || !reviewNote.trim()" @click="review('PASS')"><Check :size="16" />放行</button><button class="danger-btn" :disabled="saving || !reviewNote.trim()" @click="review('REJECT')"><X :size="16" />拒绝</button></div></template><p v-else class="form-help">{{ selected.reviewDecision ? `${selected.reviewer || ''} 已作出 ${selected.reviewDecision} 决策：${selected.reviewNote || ''}` : '当前账号仅可查看此事件。' }}</p></div></AppDrawer>
    <AppDrawer v-if="drawer === 'list'" title="新增名单" description="LIST MANAGEMENT" @close="drawer = null"><div class="risk-detail"><label>名单类型<select v-model="listForm.listType"><option>BLACK</option><option>WHITE</option><option>GREY</option></select></label><label>对象类型<select v-model="listForm.subjectType"><option>MERCHANT</option><option>EMAIL</option><option>PHONE</option><option>IP</option><option>DEVICE</option><option>CARD</option></select></label><label>对象标识<input v-model="listForm.subjectValue" placeholder="仅用于本地哈希，不会保存原文" /></label><label>处置标签<input v-model="listForm.label" placeholder="例如 已确认盗刷" /></label><label>失效时间（可选）<input v-model="listForm.expiresAt" type="datetime-local" /></label><button class="primary-btn drawer-submit" :disabled="saving || !listForm.subjectValue || !listForm.label" @click="saveList">保存名单</button></div></AppDrawer>
  </section>
</template>
