<script setup lang="ts">
import { onMounted, ref } from "vue";
import { LoaderCircle, Play, Save, Search } from "lucide-vue-next";
import { getMerchants, type Merchant } from "../merchant/api";
import { getActiveCurrencies, type Currency } from "../master-data/api";
import { changeSettlementRuleStatus, getSettlementBatch, getSettlementRules, runSettlementBatch, saveSettlementRule, type SettlementRule } from "./api";

const emit = defineEmits<{ notice: [message: string] }>();
const merchants = ref<Merchant[]>([]), currencies = ref<Currency[]>([]), rules = ref<SettlementRule[]>([]);
const loading = ref(false), saving = ref(false), batchId = ref(""), batch = ref<Record<string, unknown> | null>(null), details = ref<Record<string, unknown>[]>([]);
const filters = ref({ merchantId: "", currency: "" });
const form = ref<SettlementRule>({ merchantId: "", currency: "USD", settlementCycle: "T1", cycleDays: 1, minSettlementAmount: 0, feeRate: 0, autoSettlement: true, status: "ACTIVE", effectiveDate: new Date().toISOString().slice(0, 10), expireDate: null });
const date = ref(new Date().toISOString().slice(0, 10));
const load = async () => { loading.value = true; try { rules.value = (await getSettlementRules(filters.value.merchantId || undefined, filters.value.currency || undefined)).items; } catch (e) { emit("notice", e instanceof Error ? e.message : "结算规则加载失败"); } finally { loading.value = false; } };
const save = async () => { const rule = { ...form.value, expireDate: form.value.expireDate || null }; if (!rule.merchantId || !rule.currency) return emit("notice", "请选择商户和币种"); if (rule.cycleDays < 0 || rule.minSettlementAmount < 0 || rule.feeRate < 0 || rule.feeRate > 1) return emit("notice", "结算参数范围无效"); if (!rule.effectiveDate || (rule.expireDate && rule.expireDate < rule.effectiveDate)) return emit("notice", "失效日期不能早于生效日期"); saving.value = true; try { await saveSettlementRule(rule); emit("notice", "结算规则已保存"); await load(); } catch (e) { emit("notice", e instanceof Error ? e.message : "结算规则保存失败"); } finally { saving.value = false; } };
const run = async () => { try { const result = await runSettlementBatch(date.value); batchId.value = result.batchId; await inspect(); emit("notice", `结算批次 ${result.batchId} 已执行`); } catch (e) { emit("notice", e instanceof Error ? e.message : "结算批次执行失败"); } };
const inspect = async () => { if (!batchId.value) return; try { const result = await getSettlementBatch(batchId.value); batch.value = result.batch; details.value = result.details; } catch (e) { emit("notice", e instanceof Error ? e.message : "结算批次加载失败"); } };
const toggleRule = async (rule: SettlementRule) => { if (!rule.id) return; try { await changeSettlementRuleStatus(rule.id, rule.status === "ACTIVE" ? "DISABLED" : "ACTIVE"); await load(); } catch (e) { emit("notice", e instanceof Error ? e.message : "结算规则状态更新失败"); } };
onMounted(async () => { try { const [m, c] = await Promise.all([getMerchants({ page: 1, pageSize: 100, status: "ACTIVE" }), getActiveCurrencies()]); merchants.value = m.items; currencies.value = c; form.value.merchantId = merchants.value[0]?.merchantId || ""; await load(); } catch (e) { emit("notice", e instanceof Error ? e.message : "结算数据加载失败"); } });
</script>
<template>
  <section class="workspace-panel management-list-page">
    <form class="management-filter-form" @submit.prevent="load"><div class="management-filter-fields"><label class="management-form-item"><span>商户</span><select v-model="filters.merchantId"><option value="">全部商户</option><option v-for="m in merchants" :key="m.merchantId" :value="m.merchantId">{{ m.name }} · {{ m.merchantId }}</option></select></label><label class="management-form-item"><span>币种</span><select v-model="filters.currency"><option value="">全部币种</option><option v-for="c in currencies" :key="c.code" :value="c.code">{{ c.name }} · {{ c.code }}</option></select></label></div><div class="management-filter-actions"><button class="outline-btn" type="submit"><Search :size="16" />查询</button></div></form>
    <div class="drawer-section"><h4>新增或更新结算规则</h4><div class="drawer-form-grid"><label class="form-field"><span>商户 <b>*</b></span><select v-model="form.merchantId"><option v-for="m in merchants" :key="m.merchantId" :value="m.merchantId">{{ m.name }} · {{ m.merchantId }}</option></select></label><label class="form-field"><span>币种 <b>*</b></span><select v-model="form.currency"><option v-for="c in currencies" :key="c.code" :value="c.code">{{ c.code }}</option></select></label><label class="form-field"><span>结算周期</span><select v-model="form.settlementCycle"><option value="T0">T0</option><option value="T1">T1</option><option value="T2">T2</option><option value="MANUAL">手工</option></select></label><label class="form-field"><span>周期天数</span><input v-model.number="form.cycleDays" type="number" min="0" /></label><label class="form-field"><span>最低结算金额</span><input v-model.number="form.minSettlementAmount" type="number" min="0" step="0.0001" /></label><label class="form-field"><span>费率</span><input v-model.number="form.feeRate" type="number" min="0" max="1" step="0.0001" /></label><label class="form-field"><span>生效日期</span><input v-model="form.effectiveDate" type="date" /></label><label class="form-field"><span>失效日期</span><input v-model="form.expireDate" type="date" /></label><label class="form-field checkbox-field"><span>自动结算</span><input v-model="form.autoSettlement" type="checkbox" />启用</label></div><button class="primary-btn" :disabled="saving" @click="save"><Save :size="16" />保存规则</button></div>
    <div class="management-list-summary"><span>商户结算规则</span><small>{{ rules.length }} 条</small></div><div v-if="loading" class="empty"><LoaderCircle class="spin" :size="22" />加载中…</div><div v-else class="record-list"><div v-for="rule in rules" :key="rule.id" class="record-row"><div><strong>{{ rule.merchantId }} · {{ rule.currency }} · {{ rule.settlementCycle }}</strong><small>周期 {{ rule.cycleDays }} 天 · 最低 {{ rule.minSettlementAmount }} · 费率 {{ rule.feeRate }} · {{ rule.effectiveDate }}</small></div><span class="status-badge" :class="'st-' + rule.status.toLowerCase()">{{ rule.status }}</span><button class="icon-btn" :title="rule.status === 'ACTIVE' ? '停用规则' : '启用规则'" @click="toggleRule(rule)">{{ rule.status === 'ACTIVE' ? '停用' : '启用' }}</button></div><div v-if="!rules.length" class="empty">暂无结算规则</div></div>
    <div class="drawer-section"><h4>执行结算批次</h4><div class="drawer-form-grid"><label class="form-field"><span>结算日期</span><input v-model="date" type="date" /></label><label class="form-field"><span>批次 ID</span><input v-model="batchId" placeholder="执行后自动填充" @change="inspect" /></label></div><button class="primary-btn" @click="run"><Play :size="16" />执行批次</button><div v-if="batch" class="settlement-detail-metrics"><div><span>批次 ID</span><strong>{{ batch.batchId }}</strong></div><div><span>结算日期</span><strong>{{ batch.settlementDate }}</strong></div><div><span>订单数</span><strong>{{ batch.totalOrders }}</strong></div><div><span>商户数</span><strong>{{ batch.totalMerchants }}</strong></div><div><span>结算总额</span><strong>{{ batch.totalAmount }}</strong></div><div><span>状态</span><strong>{{ batch.status }}</strong></div></div><div v-if="details.length" class="table-wrap"><table class="data-table"><thead><tr><th>明细 ID</th><th>订单 ID</th><th>商户</th><th>币种</th><th>结算金额</th><th>状态</th></tr></thead><tbody><tr v-for="detail in details" :key="String(detail.detailId)"><td class="mono">{{ detail.detailId }}</td><td class="mono">{{ detail.orderId }}</td><td>{{ detail.merchantId }}</td><td>{{ detail.currency }}</td><td>{{ detail.settlementAmount }}</td><td>{{ detail.status }}</td></tr></tbody></table></div></div>
  </section>
</template>
