<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue";
import { LoaderCircle, Pencil, Plus, RefreshCw, Save, ToggleLeft } from "lucide-vue-next";
import { changeProductCapabilityStatus, changeProductStatus, createProduct, createProductCapability, getProductCapabilities, getProducts, updateProduct, updateProductCapability, type Product, type ProductCapability, type ProductPayload } from "./api";
import { hasPermission } from "../../auth";
import AppPagination from "../../components/AppPagination.vue";
import AppDrawer from "../../components/AppDrawer.vue";
import { getActiveCountries, getActiveCurrencies, type Country, type Currency } from "../master-data/api";

const emit = defineEmits<{ notice: [message: string] }>();
const products = ref<Product[]>([]), selected = ref<Product | null>(null), capabilities = ref<ProductCapability[]>([]), editingCapability = ref<ProductCapability | null>(null);
const loading = ref(false), saving = ref(false), editorOpen = ref(false);
const filters = ref({ status: "", productType: "" }), page = ref({ current: 1, pageSize: 20, total: 0 }), capabilityPage = ref({ current: 1, pageSize: 20, total: 0 });
const blank = (): ProductPayload & { productCode: string } => ({ productCode: "", name: "", productType: "PAYIN", accessMode: "DIRECT", defaultCountry: "US", defaultCurrency: "USD", description: "", statementDescriptor: "" });
const form = ref(blank()), capabilityForm = ref({ country: "US", currency: "USD", paymentMethod: "CARD", minAmount: 1, maxAmount: 10000, supportsRefund: true });
const countries = ref<Country[]>([]), defaultCurrencies = ref<Currency[]>([]), capabilityCurrencies = ref<Currency[]>([]);
const activeCapabilities = computed(() => products.value.reduce((sum, item) => sum + item.activeCapabilityCount, 0));
const alert = (error: unknown, fallback: string) => emit("notice", error instanceof Error ? error.message : fallback);
async function load(current = page.value.current) { loading.value = true; try { const r = await getProducts({ page: current, pageSize: page.value.pageSize, ...filters.value }); products.value = r.items; page.value = { current: r.page, pageSize: r.pageSize, total: r.total }; } catch (e) { alert(e, "产品加载失败"); } finally { loading.value = false; } }
async function loadCapabilities(current = 1) { if (!selected.value) return; const r = await getProductCapabilities(selected.value.productCode, { page: current, pageSize: capabilityPage.value.pageSize }); capabilities.value = r.items; capabilityPage.value = { current: r.page, pageSize: r.pageSize, total: r.total }; }
async function select(product: Product) { selected.value = product; editorOpen.value = false; editingCapability.value = null; await loadCapabilities(); }
function newProduct() { selected.value = null; form.value = blank(); editorOpen.value = true; }
function editProduct(product: Product) { selected.value = product; form.value = { productCode: product.productCode, name: product.name, productType: product.productType, accessMode: product.accessMode, defaultCountry: product.defaultCountry, defaultCurrency: product.defaultCurrency, description: product.description || "", statementDescriptor: product.statementDescriptor || "" }; editorOpen.value = true; }
function changeProductType() { if (form.value.productType === "PAYOUT") form.value.accessMode = null; else if (!form.value.accessMode) form.value.accessMode = "DIRECT"; }
async function saveProduct() { saving.value = true; try { if (selected.value) await updateProduct(selected.value.productCode, form.value); else await createProduct(form.value); editorOpen.value = false; await load(); emit("notice", "产品已保存"); } catch (e) { alert(e, "产品保存失败"); } finally { saving.value = false; } }
async function toggle(product: Product) { try { Object.assign(product, await changeProductStatus(product.productCode, product.status === "ACTIVE" ? "DISABLED" : "ACTIVE")); emit("notice", "产品状态已更新"); } catch (e) { alert(e, "产品状态更新失败"); } }
function editCapability(item: ProductCapability) { editingCapability.value = item; capabilityForm.value = { country: item.country, currency: item.currency, paymentMethod: item.paymentMethod, minAmount: item.minAmount, maxAmount: item.maxAmount, supportsRefund: item.supportsRefund }; }
async function saveCapability() { if (!selected.value) return; saving.value = true; const current = editingCapability.value; try { if (current) await updateProductCapability(selected.value.productCode, current.capabilityId, capabilityForm.value); else await createProductCapability(selected.value.productCode, capabilityForm.value); editingCapability.value = null; await loadCapabilities(current ? capabilityPage.value.current : 1); await load(); emit("notice", "支付能力已保存"); } catch (e) { alert(e, "能力保存失败"); } finally { saving.value = false; } }
async function toggleCapability(item: ProductCapability) { if (!selected.value) return; try { const r = await changeProductCapabilityStatus(selected.value.productCode, item.capabilityId, item.status === "ACTIVE" ? "DISABLED" : "ACTIVE"); capabilities.value = capabilities.value.map(v => v.capabilityId === r.capabilityId ? r : v); emit("notice", "支付能力状态已更新"); } catch (e) { alert(e, "能力状态更新失败"); } }
watch(() => form.value.defaultCountry, async (countryCode) => {
  if (!countryCode) return;
  defaultCurrencies.value = await getActiveCurrencies(countryCode);
  if (!defaultCurrencies.value.some((item) => item.code === form.value.defaultCurrency)) form.value.defaultCurrency = defaultCurrencies.value[0]?.code || "";
});
watch(() => capabilityForm.value.country, async (countryCode) => {
  if (!countryCode) return;
  capabilityCurrencies.value = await getActiveCurrencies(countryCode);
  if (!capabilityCurrencies.value.some((item) => item.code === capabilityForm.value.currency)) capabilityForm.value.currency = capabilityCurrencies.value[0]?.code || "";
});
onMounted(async () => { await load(); try { countries.value = await getActiveCountries(); defaultCurrencies.value = await getActiveCurrencies(form.value.defaultCountry); capabilityCurrencies.value = await getActiveCurrencies(capabilityForm.value.country); } catch (e) { alert(e, "国家与币种基础数据加载失败"); } });
</script>

<template>
  <section class="workspace-panel product-workspace">
    <div class="panel-title"><div><span class="eyebrow">PAYMENT PRODUCTS</span><h3>产品管理</h3><small>产品主数据、适用市场与支付能力配置</small></div><div class="button-row"><button class="outline-btn" @click="load()"><RefreshCw :size="16" />刷新</button><button v-if="hasPermission('product:create')" class="primary-btn" @click="newProduct"><Plus :size="16" />新建产品</button></div></div>
    <div class="product-kpis"><div><span>产品总数</span><strong>{{ page.total }}</strong></div><div><span>当前页启用能力</span><strong>{{ activeCapabilities }}</strong></div><div><span>已选产品</span><strong>{{ selected?.productCode || "-" }}</strong></div></div>
    <div class="product-filters"><select v-model="filters.status"><option value="">全部状态</option><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></select><select v-model="filters.productType"><option value="">全部类型</option><option value="PAYIN">收款 PAYIN</option><option value="PAYOUT">出款 PAYOUT</option></select><button class="outline-btn" @click="load(1)">筛选</button></div>
    <div v-if="loading" class="empty"><LoaderCircle class="spin" :size="22" />加载中…</div>
    <div v-else class="table-wrap"><table class="data-table product-table"><thead><tr><th>产品</th><th>类型 / 接入</th><th>默认市场</th><th>支付方式</th><th class="num">启用能力</th><th>状态</th><th class="actions">操作</th></tr></thead><tbody><tr v-for="product in products" :key="product.productCode" :class="{ selected: selected?.productCode === product.productCode }" @click="select(product)"><td><strong>{{ product.name }}</strong><small class="mono">{{ product.productCode }}</small></td><td><strong>{{ product.productType }}</strong><small>{{ product.accessMode || "不适用" }}</small></td><td><strong>{{ product.defaultCountry }}/{{ product.defaultCurrency }}</strong><small>{{ product.supportedCurrencies || "未配置币种" }}</small></td><td>{{ product.supportedPaymentMethods || "未配置" }}</td><td class="num">{{ product.activeCapabilityCount }}</td><td><span class="status-badge" :class="'st-' + product.status.toLowerCase()">{{ product.status }}</span></td><td class="actions"><button v-if="hasPermission('product:update')" class="icon-btn" title="编辑产品" @click.stop="editProduct(product)"><Pencil :size="16" /></button><button v-if="hasPermission('product:status')" class="icon-btn" title="切换状态" @click.stop="toggle(product)"><ToggleLeft :size="16" /></button></td></tr></tbody></table></div>
    <AppPagination :page="page.current" :page-size="page.pageSize" :total="page.total" noun="个产品" @change="load" />
    <AppDrawer v-if="editorOpen" :title="selected ? '编辑产品' : '新建产品'" description="PAYMENT PRODUCT" @close="editorOpen = false"><form class="product-drawer-form" @submit.prevent="saveProduct"><section class="drawer-section"><div class="drawer-section-heading"><div><h4>基础信息</h4><small>产品类型定义资金方向，创建后产品编码不可修改。</small></div></div><div class="drawer-form-grid"><label v-if="!selected" class="form-field"><span>产品编码 <b>*</b></span><input v-model="form.productCode" maxlength="64" placeholder="例如 CARD-US-USD" @input="form.productCode = form.productCode.toUpperCase()" /><small>用于商户开通、路由和费率配置。</small></label><label class="form-field"><span>产品名称 <b>*</b></span><input v-model="form.name" maxlength="128" placeholder="例如 美国卡支付" /><small>后台运营人员可识别的产品名称。</small></label><label class="form-field"><span>产品类型 <b>*</b></span><select v-model="form.productType" @change="changeProductType"><option value="PAYIN">收款 PAYIN</option><option value="PAYOUT">出款 PAYOUT</option></select><small>收款用于接入支付方式；出款用于向收款方付款。</small></label><label v-if="form.productType === 'PAYIN'" class="form-field"><span>接入模式 <b>*</b></span><select v-model="form.accessMode"><option value="DIRECT">直连 DIRECT</option><option value="AGGREGATED">聚合 AGGREGATED</option></select><small>直连使用独立渠道，聚合支持统一接入与路由。</small></label></div></section><section class="drawer-section"><div class="drawer-section-heading"><div><h4>默认市场</h4><small>选择国家后仅显示已启用的关联币种。</small></div></div><div class="drawer-form-grid"><label class="form-field"><span>默认国家/地区 <b>*</b></span><select v-model="form.defaultCountry"><option v-for="item in countries" :key="item.code" :value="item.code">{{ item.name }} · {{ item.code }}</option></select><small>由国家/地区管理模块统一维护。</small></label><label class="form-field"><span>默认币种 <b>*</b></span><select v-model="form.defaultCurrency"><option v-for="item in defaultCurrencies" :key="item.code" :value="item.code">{{ item.name }} · {{ item.code }}</option></select><small>仅显示该国家/地区可用的币种。</small></label></div></section><section class="drawer-section"><div class="drawer-section-heading"><div><h4>展示信息</h4><small>该信息用于运营识别和客户账单展示。</small></div></div><div class="drawer-form-grid"><label class="form-field"><span>账单描述符</span><input v-model="form.statementDescriptor" maxlength="22" placeholder="例如 DEMO PAYMENT" /><small>最多 22 个字符。</small></label><label class="form-field form-field-full"><span>产品描述</span><input v-model="form.description" maxlength="1000" placeholder="填写适用商户、商品或服务说明" /><small>最多 1000 个字符，不填写时可后续补充。</small></label></div></section><div class="product-drawer-actions"><button class="outline-btn" type="button" @click="editorOpen = false">取消</button><button class="primary-btn" type="submit" :disabled="saving || !form.name.trim() || (!selected && !form.productCode.trim()) || !form.defaultCountry || !form.defaultCurrency || (form.productType === 'PAYIN' && !form.accessMode)"><Save :size="16" />{{ selected ? '保存产品' : '创建产品' }}</button></div></form></AppDrawer>
    <div v-if="selected && !editorOpen" class="product-detail"><div class="section-heading"><div><span class="eyebrow">CAPABILITY MATRIX</span><h4>{{ selected.name }} · {{ selected.productCode }}</h4></div><span>{{ selected.description || "未填写产品描述" }}</span></div><div class="capability-form"><select v-model="capabilityForm.country"><option v-for="item in countries" :key="item.code" :value="item.code">{{ item.name }} · {{ item.code }}</option></select><select v-model="capabilityForm.currency"><option v-for="item in capabilityCurrencies" :key="item.code" :value="item.code">{{ item.name }} · {{ item.code }}</option></select><input v-model="capabilityForm.paymentMethod" placeholder="支付方式" /><input v-model.number="capabilityForm.minAmount" type="number" min="0.01" step="0.01" placeholder="最小金额" /><input v-model.number="capabilityForm.maxAmount" type="number" min="0.01" step="0.01" placeholder="最大金额" /><label class="menu-visible"><input v-model="capabilityForm.supportsRefund" type="checkbox" />支持退款</label><button class="primary-btn" :disabled="saving" @click="saveCapability"><Plus :size="16" />{{ editingCapability ? "保存能力" : "新增能力" }}</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>支付方式</th><th>市场</th><th class="num">交易限额</th><th>退款</th><th>状态</th><th class="actions">操作</th></tr></thead><tbody><tr v-for="item in capabilities" :key="item.capabilityId"><td><strong>{{ item.paymentMethod }}</strong></td><td>{{ item.country }}/{{ item.currency }}</td><td class="num">{{ item.minAmount }} - {{ item.maxAmount }}</td><td>{{ item.supportsRefund ? "支持" : "不支持" }}</td><td><span class="status-badge" :class="'st-' + item.status.toLowerCase()">{{ item.status }}</span></td><td class="actions"><button class="icon-btn" title="编辑能力" @click="editCapability(item)"><Pencil :size="16" /></button><button class="icon-btn" title="切换状态" @click="toggleCapability(item)"><ToggleLeft :size="16" /></button></td></tr><tr v-if="!capabilities.length"><td colspan="6" class="empty">暂无支付能力</td></tr></tbody></table></div><AppPagination :page="capabilityPage.current" :page-size="capabilityPage.pageSize" :total="capabilityPage.total" noun="项能力" @change="loadCapabilities" /></div>
  </section>
</template>
