import { request } from "../../api";
import { getRoles } from "../permission/api";
export type PageResponse<T> = { items: T[]; page: number; pageSize: number; total: number };
export type AdminUser = { id: number; username: string; displayName: string; status: string; roles: string[] };
const pageQuery = (params: { page?: number; pageSize?: number }) => new URLSearchParams({ page: String(params.page || 1), pageSize: String(params.pageSize || 20) });
export const getUsers = (params: { page?: number; pageSize?: number } = {}) => request<PageResponse<AdminUser>>(`/admin/v1/users?${pageQuery(params)}`);
export const createUser = (payload: { username: string; password: string; displayName: string; roles: string[] }) => request<AdminUser>("/admin/v1/users", { method: "POST", body: JSON.stringify(payload) });
export const updateUser = (id: number, payload: { displayName: string; roles: string[] }) => request<AdminUser>(`/admin/v1/users/${id}`, { method: "PUT", body: JSON.stringify(payload) });
export const changeUserStatus = (id: number, status: string) => request<AdminUser>(`/admin/v1/users/${id}/status`, { method: "PATCH", body: JSON.stringify({ status }) });
export const resetUserPassword = (id: number, newPassword: string) => request<void>(`/admin/v1/users/${id}/reset-password`, { method: "POST", body: JSON.stringify({ newPassword }) });
export type UserDataScope = { userId: number; merchantIds: string[] };
export const getUserDataScope = (id: number) => request<UserDataScope>(`/admin/v1/data-scopes/users/${id}`);
export const updateUserDataScope = (id: number, merchantIds: string[]) => request<UserDataScope>(`/admin/v1/data-scopes/users/${id}`, { method: "PUT", body: JSON.stringify({ merchantIds }) });
export { getRoles };
