import { request } from "../../api";
export type PageResponse<T> = { items: T[]; page: number; pageSize: number; total: number };
export type Merchant = { merchantId: string; name: string; status: string; createdAt: string; updatedAt: string };
export type MerchantProfile = {
  merchantId: string;
  legalName: string;
  businessType: "COMPANY" | "INDIVIDUAL" | "NON_PROFIT" | "GOVERNMENT";
  registeredCountry: string;
  industry?: string;
  businessUrl?: string;
  productDescription?: string;
  statementDescriptor?: string;
  supportEmail?: string;
  supportPhone?: string;
  supportUrl?: string;
  addressLine1?: string;
  addressLine2?: string;
  addressCity?: string;
  addressState?: string;
  addressPostalCode?: string;
  riskLevel: string;
  taxIdentifier?: string;
  createdAt?: string;
  updatedAt?: string;
};
export type MerchantContact = { id: number; merchantId: string; contactType: string; contactName: string; email?: string; phone?: string; notifyEnabled: boolean; createdAt?: string; updatedAt?: string };
export type MerchantCredential = { credentialId: string; merchantId: string; credentialType: string; secretHint: string; status: string; createdAt?: string; rotatedAt?: string; revokedAt?: string };
export type RotatedCredential = { credentialId: string; credentialType: string; secret: string; createdAt: string };
export type MerchantProduct = { bindingId: string; merchantId: string; merchantName: string; productCode: string; productName: string; status: string; createdAt: string; updatedAt: string; supportedPaymentMethods: string };
type MerchantListParams = {
  page?: number;
  pageSize?: number;
  merchantName?: string;
  merchantId?: string;
  status?: string;
  createdFrom?: string;
  createdTo?: string;
};
const pageQuery = (params: MerchantListParams) => {
  const query = new URLSearchParams({ page: String(params.page || 1), pageSize: String(params.pageSize || 20) });
  (["merchantName", "merchantId", "status", "createdFrom", "createdTo"] as const).forEach((key) => {
    if (params[key]) query.set(key, params[key]);
  });
  return query;
};
export const getMerchants = (params: MerchantListParams = {}) => request<PageResponse<Merchant>>(`/admin/v1/merchants?${pageQuery(params)}`);
export const getMerchant = (id: string) => request<Merchant>(`/admin/v1/merchants/${encodeURIComponent(id)}`);
export const createMerchant = (payload: { name: string; merchantId?: string }) => request<Merchant>("/admin/v1/merchants", { method: "POST", body: JSON.stringify(payload) });
export const updateMerchant = (id: string, payload: { name: string }) => request<Merchant>(`/admin/v1/merchants/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify(payload) });
export const changeMerchantStatus = (id: string, status: string) => request<Merchant>(`/admin/v1/merchants/${encodeURIComponent(id)}/status`, { method: "PATCH", body: JSON.stringify({ status }) });
export const getMerchantProfile = (id: string) => request<MerchantProfile>(`/admin/v1/merchants/${encodeURIComponent(id)}/profile`);
export const updateMerchantProfile = (id: string, payload: Omit<MerchantProfile, "merchantId" | "createdAt" | "updatedAt">) => request<MerchantProfile>(`/admin/v1/merchants/${encodeURIComponent(id)}/profile`, { method: "PUT", body: JSON.stringify(payload) });
export const getMerchantContacts = (id: string) => request<MerchantContact[]>(`/admin/v1/merchants/${encodeURIComponent(id)}/contacts`);
export const createMerchantContact = (id: string, payload: Omit<MerchantContact, "id" | "merchantId" | "createdAt" | "updatedAt">) => request<MerchantContact>(`/admin/v1/merchants/${encodeURIComponent(id)}/contacts`, { method: "POST", body: JSON.stringify(payload) });
export const updateMerchantContact = (merchantId: string, contactId: number, payload: Omit<MerchantContact, "id" | "merchantId" | "createdAt" | "updatedAt">) => request<MerchantContact>(`/admin/v1/merchants/${encodeURIComponent(merchantId)}/contacts/${contactId}`, { method: "PUT", body: JSON.stringify(payload) });
export const deleteMerchantContact = (merchantId: string, contactId: number) => request<void>(`/admin/v1/merchants/${encodeURIComponent(merchantId)}/contacts/${contactId}`, { method: "DELETE" });
export const getMerchantCredentials = (id: string) => request<MerchantCredential[]>(`/admin/v1/merchants/${encodeURIComponent(id)}/credentials`);
export const rotateMerchantCredential = (id: string, credentialType: "API" | "WEBHOOK") => request<RotatedCredential>(`/admin/v1/merchants/${encodeURIComponent(id)}/credentials/rotate`, { method: "POST", body: JSON.stringify({ credentialType }) });
export const revokeMerchantCredential = (id: string, credentialId: string) => request<void>(`/admin/v1/merchants/${encodeURIComponent(id)}/credentials/${encodeURIComponent(credentialId)}/revoke`, { method: "POST" });
export const getMerchantProducts = (params: { page?: number; pageSize?: number } = {}) => request<PageResponse<MerchantProduct>>(`/admin/v1/merchant-products?${pageQuery(params)}`);
export const bindMerchantProduct = (payload: { merchantId: string; productCode: string }) => request<MerchantProduct>("/admin/v1/merchant-products", { method: "POST", body: JSON.stringify(payload) });
export const updateMerchantProduct = (id: string, payload: { merchantId: string; productCode: string }) => request<MerchantProduct>(`/admin/v1/merchant-products/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify(payload) });
export const changeMerchantProductStatus = (id: string, status: string) => request<void>(`/admin/v1/merchant-products/${encodeURIComponent(id)}/status`, { method: "PATCH", body: JSON.stringify({ status }) });
